# for loop Tutorial

# Tutorial 1: use for loop to iterate over the string sequence
for ch in "Ahsan":
    print(ch)


# Tutorial 2: use for loop to iterate over the sequence of numbers
# Note:   range(Start_number, Stop_number, step_size)
for i in range(5):   # iterates i on the sequence generated by range function
    print(i)         # this code block will repeat 5 times

# Tutorial 3: print the multiplication table of the given number
num = int(input("Enter a number: "))

for i in range(1,10):    # same as range(1,5,1)
    print(f"{num} x {i} = ", num*i)
